package com.codename1.demos.signin;


import static com.codename1.ui.CN.getCurrentForm;

import java.io.IOException;

import com.codename1.social.Login;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class SignIn {

    private Form loginForm;
    private Resources theme;
    private Login login;

    public void init(Object context) {
        try {
        	theme = Resources.openLayered("/theme");
        	UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch (IOException e) {
        	
        }
    }
    
    public void start() {
        loginForm = new Form("Inscription");
        loginForm.setLayout(new BorderLayout());
        Container center = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        center.setUIID("ContainerWithPadding");
        
        Image logo = theme.getImage("mlogo.png");
        Label l = new Label(logo);
        Container flow = new Container(new FlowLayout(Component.CENTER));
        flow.addComponent(l);
        center.addComponent(flow);
        
        final TextField username = new TextField();
        username.setHint("Username");
        final TextField pass = new TextField();
        pass.setHint("Password");
        pass.setConstraint(TextField.PASSWORD);
        
        final TextField email = new TextField();
        email.setHint("Email");
        email.setConstraint(TextField.EMAILADDR);
        
        final TextField phone = new TextField();
        phone.setHint("Telephone");
        phone.setConstraint(TextField.PHONENUMBER);
        
        center.addComponent(username);
        center.addComponent(pass);
        center.addComponent(email);
        center.addComponent(phone);
        
        Button signIn = new Button("Soumettre");
        
        signIn.addActionListener((ActionListener) (ActionEvent evt) -> {
        	if (username.getText().length()==0||pass.getText().length()==0)
        	{
        		return;
        	}
        	UserForm userForm = new UserForm(username.getText(), pass.getText(), email.getText(), phone.getText());
        	userForm.show();
        });
        
        center.addComponent(signIn);
        loginForm.addComponent(BorderLayout.CENTER, center);
        loginForm.show(); 
        
    }

    public void stop() {
    }
    
    public void destroy() {
    }

}





































